CREATE TABLE SENTENCES
(
    ID                  BIGSERIAL PRIMARY KEY,
    NAME                CHARACTER VARYING NOT NULL,
    ORIGINAL_SENTENCE   CHARACTER VARYING NOT NULL,
    POSTFIX_FORM        CHARACTER VARYING NOT NULL
);
CREATE TABLE CONTEXT_PARAMETERS
(
    ID                  BIGSERIAL PRIMARY KEY,
    NAME                CHARACTER VARYING NOT NULL,
    TYPE                CHARACTER VARYING NOT NULL,
    SENTENCE_ID         BIGINT NOT NULL,
    CONSTRAINT FK_SENTENCES_CONTEXT_PARAMETERS FOREIGN KEY (SENTENCE_ID) REFERENCES SENTENCES (ID)
);

